import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select

driver = webdriver.Chrome()
driver.get('https://www.techlistic.com/p/selenium-practice-form.html')
firstname_input = driver.find_element(By.NAME, 'firstname')
time.sleep(2)
firstname_input.send_keys('Ghozal')
lastname_input = driver.find_element(By.NAME, 'lastname')
time.sleep(2)
lastname_input.send_keys('imam')
gender_input = driver.find_element(By.ID, 'sex-0')
time.sleep(2)
gender_input.click()
time.sleep(2)
years_of_experience = driver.find_element(By.ID, 'exp-1')
time.sleep(2)
years_of_experience.click()
time.sleep(2)
date_input = driver.find_element(By.ID, 'datepicker')
date_input.send_keys('20 Januari 2025')
time.sleep(2)
professionManual = driver.find_element(By.ID, 'profession-0')
professionManual.click()
time.sleep(2)
professionAutomation = driver.find_element(By.ID, 'profession-1')
professionAutomation.click()
time.sleep(2)
automation_tools = driver.find_element(By.ID, 'tool-2')
automation_tools.click()
time.sleep(2)
dropdown = Select(driver.find_element(By.ID, 'continents'))
dropdown.select_by_visible_text('Europe')
time.sleep(2)
option = driver.find_element(By.XPATH, '//select[@id="selenium_commands"]/option[text()="Wait Commands"]')
option.click()
file_input = driver.find_element(By.ID, 'photo')
file_path = r'C:\Users\ghoza\OneDrive\Pictures\peta.png'
file_input.send_keys(file_path)
time.sleep(2)
button = driver.find_element(By.ID, 'submit')
button.click()

time.sleep(5)
driver.quit()